### ISSUE TITLE
Included pdfid.py is not the most recent version available

### ISSUE THREAD

**Issue by pdfkungfoo** [hiddenillusion/AnalyzePDF#1]
Is there a particular reason why you included version 0.0.12 (dated 2012/03/03) of pdfid.py?

The most recent release is 0.1.0 (dated 2013/02/10).

**Comment by hiddenillusion** [comment]
Sure is - that was the most recent version at the time I initially started my research.  I know there have been some recent updates to pdfid, as you mentioned, but as I stated in the post I wanted to make sure the tool worked as expected.  Once I get around to verifying nothing breaks with the latest version I will remove this older copy.

**Comment by pdfkungfoo** [comment]
Ha!, I discovered your blogpost (with your explicit hint about why you use the older pdfid.py) only after I say your github repo.   :-)

Thanks!
