### ISSUE TITLE
pdf_rules.yara: header_evasion should use $magic in (1..1024)

### ISSUE THREAD

**Issue by pdfkungfoo** [hiddenillusion/AnalyzePDF#3]
Shouldn't the rule _header_evasion_ use `$magic in (1..1024)` (instead of `(5..1024)`?

**Comment by hiddenillusion** [comment]
You can write the rule anyway you'd like.  For me, I want to detect a file that has it lower than where it's normally seen.

**Comment by pdfkungfoo** [comment]
Yes, but my modified rule _also_ has it lower (it's not `(0..1024)`.

**Comment by hiddenillusion** [comment]
The $magic I'm flagging on is 4 bytes so if looking for it from 5 and below how is that any different than looking at it from 1 and below?  Looking for it at 1 and below would find the same thing - the 4 byte header isn't going to fit at just 0.  Again, write the rule how ever you feel comfortable.

**Comment by pdfkungfoo** [comment]
In my understanding, your version of the rule would miss a simple newline character that could be inserted before the $magic.

However, maybe I need to become more familiar with YARA and also experiment with its rules...
